TOTAL_BUDGET = 1500

GAS_PRICE = 600
FOOD_PRICE = 300
ACCOMMODATION_PRICE = 200

SOUVENIR_UNIT_PRICE = 25

REMAINING_BUDGET = (TOTAL_BUDGET
                    - GAS_PRICE
                    - FOOD_PRICE
                    - ACCOMMODATION_PRICE)

POTENTIAL_SOUVENIR_COUNT = REMAINING_BUDGET // SOUVENIR_UNIT_PRICE

print(POTENTIAL_SOUVENIR_COUNT)
